name: Context Examples

on: ['push']

jobs:
    my-context:
        runs-on: ubuntu-latest
        steps:
            - name: "My Step"
              run: echo "Hello! {github.action}"
              env:
                MY_ACTION: ${{ github.action}}
